sudo: required
language: node_js
node_js: 14
cache: npm
notifications:
  email: false
services:
  - docker
before_install:
  - docker build -t miguelleal96/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true miguelleal96/docker-react npm run test